# Change these first
owner: pokanop # Your GitHub username
repo: uptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Pokanop Apps Frontend
    url: https://pokanop.com
  - name: Pokanop Apps Backend
    url: $SECRET_BACKEND_URL
  - name: Uptime
    url: https://uptime.pokanop.com
  - name: Jenkins
    url: $SECRET_JENKINS_URL
    expectedStatusCodes:
      - 200
      - 403
  - name: Bitbucket
    url: $SECRET_BITBUCKET_URL
  - name: Confluence
    url: $SECRET_CONFLUENCE_URL
  - name: Jira
    url: $SECRET_JIRA_URL
  - name: Docker Registry
    url: $SECRET_REGISTRY_URL
    headers:
      - 'Authorization: Basic $SECRET_REGISTRY_AUTH'
  - name: Sourcegraph
    url: $SECRET_SOURCEGRAPH_URL

assignees:
  - saheljalal

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: uptime.pokanop.com
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime
  introTitle: '**Pokanop Apps** uptime monitor and status page, powered entirely by GitHub.'
  introMessage: This status page uses **real-time** data from our [GitHub repository](https://github.com/pokanop/uptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
